-- =========================================================
-- Beneficiary Attachment Types Seed
-- أنواع مرفقات المستفيد الأساسية
-- SAFE SCRIPT
-- =========================================================

insert into public.attachment_types (
  code,
  name_ar,
  name_en,
  category,
  entity_type,
  section_id,
  path_segment,
  is_required,
  allowed_extensions,
  allowed_mime_types,
  max_file_size_mb,
  is_image_required,
  allow_multiple,
  naming_strategy,
  sort_order,
  is_active,
  notes,
  created_at,
  updated_at
)
values
(
  'personal_photo',
  'الصورة الشخصية',
  'Personal Photo',
  'beneficiary_form',
  'beneficiary',
  (select id from public.attachment_sections where section_code = 'beneficiary_static' limit 1),
  'pics',
  true,
  'jpg,jpeg,png',
  'image/jpeg,image/png',
  2,
  true,
  false,
  'file_number',
  10,
  true,
  'صورة المستفيد الشخصية',
  now(),
  now()
),
(
  'birth_certificate',
  'شهادة الميلاد',
  'Birth Certificate',
  'beneficiary_form',
  'beneficiary',
  (select id from public.attachment_sections where section_code = 'beneficiary_static' limit 1),
  'birth_certificate',
  false,
  'jpg,jpeg,png,pdf',
  'image/jpeg,image/png,application/pdf',
  5,
  false,
  false,
  'file_number',
  20,
  true,
  'شهادة ميلاد المستفيد',
  now(),
  now()
),
(
  'father_death_certificate',
  'شهادة وفاة الأب',
  'Father Death Certificate',
  'beneficiary_form',
  'beneficiary',
  (select id from public.attachment_sections where section_code = 'beneficiary_static' limit 1),
  'father_death_certificate',
  false,
  'jpg,jpeg,png,pdf',
  'image/jpeg,image/png,application/pdf',
  5,
  false,
  false,
  'file_number',
  30,
  true,
  'شهادة وفاة الأب',
  now(),
  now()
),
(
  'form1',
  'استمارة 1',
  'Form 1',
  'beneficiary_form',
  'beneficiary',
  (select id from public.attachment_sections where section_code = 'beneficiary_static' limit 1),
  'form1',
  false,
  'jpg,jpeg,png,pdf',
  'image/jpeg,image/png,application/pdf',
  5,
  false,
  false,
  'file_number',
  40,
  true,
  'استمارة رقم 1',
  now(),
  now()
),
(
  'form2',
  'استمارة 2',
  'Form 2',
  'beneficiary_form',
  'beneficiary',
  (select id from public.attachment_sections where section_code = 'beneficiary_static' limit 1),
  'form2',
  false,
  'jpg,jpeg,png,pdf',
  'image/jpeg,image/png,application/pdf',
  5,
  false,
  false,
  'file_number',
  50,
  true,
  'استمارة رقم 2',
  now(),
  now()
),
(
  'identity_document',
  'وثيقة الهوية',
  'Identity Document',
  'beneficiary_form',
  'beneficiary',
  (select id from public.attachment_sections where section_code = 'beneficiary_static' limit 1),
  'identity_document',
  false,
  'jpg,jpeg,png,pdf',
  'image/jpeg,image/png,application/pdf',
  5,
  false,
  false,
  'file_number',
  60,
  true,
  'بطاقة أو وثيقة إثبات هوية',
  now(),
  now()
)
on conflict (code) do update
set
  name_ar = excluded.name_ar,
  name_en = excluded.name_en,
  category = excluded.category,
  entity_type = excluded.entity_type,
  section_id = excluded.section_id,
  path_segment = excluded.path_segment,
  is_required = excluded.is_required,
  allowed_extensions = excluded.allowed_extensions,
  allowed_mime_types = excluded.allowed_mime_types,
  max_file_size_mb = excluded.max_file_size_mb,
  is_image_required = excluded.is_image_required,
  allow_multiple = excluded.allow_multiple,
  naming_strategy = excluded.naming_strategy,
  sort_order = excluded.sort_order,
  is_active = true,
  notes = excluded.notes,
  updated_at = now();